version: '3.8'

services:
  hell_app:
    build: .
    container_name: hell_core
    restart: always
    network_mode: "host"
    privileged: true # Damos privilegios totales para asegurar bind en puertos bajos (<1024)
    environment:
      - MY_IP=${MY_IP:-127.0.0.1}
    volumes:
      - ./logs:/app/logs
      - ./scripts:/app/scripts
    cap_add:
      - NET_ADMIN
      - NET_RAW
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  hell_db:
    image: mysql:8.0
    container_name: hell_db_backend
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root_hell_2026}
    volumes:
      - hell_data:/var/lib/mysql
