version: '3.8'

services:
  hell_app:
    build: .
    container_name: hell_core
    restart: always
    network_mode: "host" # Usamos modo host para mayor realismo y soporte de ICMP Tarpit
    environment:
      - MY_IP=${MY_IP:-127.0.0.1}
      - HELL_MESH_PEERS=${HELL_MESH_PEERS:-}
      - HELL_NODE_ID=NODE-SFO-01
    volumes:
      - ./logs:/app/logs
      - ./scripts:/app/scripts
      - ./templates:/app/templates
    cap_add:
      - NET_ADMIN # Necesario para MSS Clamping e Iptables
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  hell_db:
    image: mysql:8.0
    container_name: hell_db_backend
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root_hell_2026}
    volumes:
      - hell_data:/var/lib/mysql
    networks:
      - hell_net

networks:
  hell_net:
    driver: bridge

volumes:
  hell_data:
